development:
  adapter: postgresql
  encoding: unicode
  database: open_exam_development
  pool: 5
  username: john
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: open_exam_test
  pool: 5
  username: john
  password:
  host: localhost
  port: 5432 

production:
  adapter: postgresql
  encoding: unicode
  database: open_exam_production
  pool: 5
  username: john
  password: 
  host: localhost
  port: 5432