require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TakequizzesController do

  # This should return the minimal set of attributes required to create a valid
  # Takequiz. As you add validations to Takequiz, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TakequizzesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all takequizzes as @takequizzes" do
      takequiz = Takequiz.create! valid_attributes
      get :index, {}, valid_session
      assigns(:takequizzes).should eq([takequiz])
    end
  end

  describe "GET show" do
    it "assigns the requested takequiz as @takequiz" do
      takequiz = Takequiz.create! valid_attributes
      get :show, {:id => takequiz.to_param}, valid_session
      assigns(:takequiz).should eq(takequiz)
    end
  end

  describe "GET new" do
    it "assigns a new takequiz as @takequiz" do
      get :new, {}, valid_session
      assigns(:takequiz).should be_a_new(Takequiz)
    end
  end

  describe "GET edit" do
    it "assigns the requested takequiz as @takequiz" do
      takequiz = Takequiz.create! valid_attributes
      get :edit, {:id => takequiz.to_param}, valid_session
      assigns(:takequiz).should eq(takequiz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Takequiz" do
        expect {
          post :create, {:takequiz => valid_attributes}, valid_session
        }.to change(Takequiz, :count).by(1)
      end

      it "assigns a newly created takequiz as @takequiz" do
        post :create, {:takequiz => valid_attributes}, valid_session
        assigns(:takequiz).should be_a(Takequiz)
        assigns(:takequiz).should be_persisted
      end

      it "redirects to the created takequiz" do
        post :create, {:takequiz => valid_attributes}, valid_session
        response.should redirect_to(Takequiz.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved takequiz as @takequiz" do
        # Trigger the behavior that occurs when invalid params are submitted
        Takequiz.any_instance.stub(:save).and_return(false)
        post :create, {:takequiz => {}}, valid_session
        assigns(:takequiz).should be_a_new(Takequiz)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Takequiz.any_instance.stub(:save).and_return(false)
        post :create, {:takequiz => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested takequiz" do
        takequiz = Takequiz.create! valid_attributes
        # Assuming there are no other takequizzes in the database, this
        # specifies that the Takequiz created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Takequiz.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => takequiz.to_param, :takequiz => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested takequiz as @takequiz" do
        takequiz = Takequiz.create! valid_attributes
        put :update, {:id => takequiz.to_param, :takequiz => valid_attributes}, valid_session
        assigns(:takequiz).should eq(takequiz)
      end

      it "redirects to the takequiz" do
        takequiz = Takequiz.create! valid_attributes
        put :update, {:id => takequiz.to_param, :takequiz => valid_attributes}, valid_session
        response.should redirect_to(takequiz)
      end
    end

    describe "with invalid params" do
      it "assigns the takequiz as @takequiz" do
        takequiz = Takequiz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Takequiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => takequiz.to_param, :takequiz => {}}, valid_session
        assigns(:takequiz).should eq(takequiz)
      end

      it "re-renders the 'edit' template" do
        takequiz = Takequiz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Takequiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => takequiz.to_param, :takequiz => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested takequiz" do
      takequiz = Takequiz.create! valid_attributes
      expect {
        delete :destroy, {:id => takequiz.to_param}, valid_session
      }.to change(Takequiz, :count).by(-1)
    end

    it "redirects to the takequizzes list" do
      takequiz = Takequiz.create! valid_attributes
      delete :destroy, {:id => takequiz.to_param}, valid_session
      response.should redirect_to(takequizzes_url)
    end
  end

end
